###########################   PROVIDER ROUTES   #################


### Registering Provider Account
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  	"name": "Harish Ponna",
   "email": "harishponna551112113@gmail.com",
   "password": "123456",
   "aadhaarNumber":333313333133,
   "gender":"male",
   "contactNumber":1234567890,
   "address":"chikkadpally hyderabad telangana",
   "role" : "Job-Provider" 
  }
###  Provider Account Activation
GET http://localhost:8080/api/accountactivation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MC4xOTc1ODQ4MjkwOTUxNTY3MywiaWF0IjoxNTg1NzM0MzU3LCJleHAiOjE2NDU3MzQzNTd9.wAXI7841bEkCF35NMC5GBa-2IptBymbs0sbqllSYi00?user=Job-Provider

### Logging into Provider Account
POST http://localhost:8080/api/user/login
Content-Type: application/json

 {  
   "email": "harishponna55@gmail.com",
   "password": "64970183",   
   "role" : "Job-Provider" 
  }

### Posting a job by provider
POST http://localhost:8080/api/jobprovider/postingjob
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjJkNTVjNDBkMDM3MmNjYmUxZjAiLCJpYXQiOjE1ODU3MzQ1MzQsImV4cCI6MTY0NTczNDUzNH0.34-59--3LTpIA1jUOsvoV7c_51KsOj4lurjGqH_7uXo

{
            "category":"yearly",
            "duration": 5,
            "title":"piano tutor",
            "description":"piano teaching for my kid",
            "preferedSkills":"pianist",
            "rateOfPayment":500,
            "preference":"any",
			       "timeSlot":"1pm-6pm",
            "keyword":"pianist",
            "jobProviderName":"Harish",
            "contactNumber": 8977700000,
            "city": "Hyderabad",
            "pincode": 500060,
            "address": "hyderabad chikkadpally"
        }

###  Showing provider his own posted jobs
GET http://localhost:8080/api/jobprovider/jobspostedtilldate/1/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjJkNTVjNDBkMDM3MmNjYmUxZjAiLCJpYXQiOjE1ODU3MzQ1MzQsImV4cCI6MTY0NTczNDUzNH0.34-59--3LTpIA1jUOsvoV7c_51KsOj4lurjGqH_7uXo


###  Job updation by Provider Account
PATCH http://localhost:8080/api/jobprovider/udpatingjob/5e8463cb5c40d0372ccbe1f4/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjJkNTVjNDBkMDM3MmNjYmUxZjAiLCJpYXQiOjE1ODU3MzQ1MzQsImV4cCI6MTY0NTczNDUzNH0.34-59--3LTpIA1jUOsvoV7c_51KsOj4lurjGqH_7uXo

{
            "category":"monthly",
            "duration": 2,
            "title":"paino tutor",
            "description":"paino teaching for my kid",
            "preferedSkills":"pianist",
            "rateOfPayment":500,
            "preference":"any",
			       "timeSlot":"1pm-6pm",
            "keyword":"pianist",
            "jobProviderName":"Harish",
            "contactNumber": 8977700000,
            "city": "Hyderabad",
            "pincode": 500060,
            "address": "hyderabad chikkadpally"
}


###  Job Deletion by Provider
DELETE http://localhost:8080/api/jobprovider/deletingjob/5e8463cb5c40d0372ccbe1f4/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjJkNTVjNDBkMDM3MmNjYmUxZjAiLCJpYXQiOjE1ODU3MzQ1MzQsImV4cCI6MTY0NTczNDUzNH0.34-59--3LTpIA1jUOsvoV7c_51KsOj4lurjGqH_7uXo


###   Uploading Profile Picture
PATCH http://localhost:8080/api/jobprovider/uploadprofilepicture
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjJkNTVjNDBkMDM3MmNjYmUxZjAiLCJpYXQiOjE1ODU3MzQ1MzQsImV4cCI6MTY0NTczNDUzNH0.34-59--3LTpIA1jUOsvoV7c_51KsOj4lurjGqH_7uXo
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="hari.jpeg"
Content-Type: image/jpeg

< C:\Users\Harish\Desktop\hari.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### udpating profile
PATCH http://localhost:8080/api/jobprovider/editprofile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjJkNTVjNDBkMDM3MmNjYmUxZjAiLCJpYXQiOjE1ODU3MzQ1MzQsImV4cCI6MTY0NTczNDUzNH0.34-59--3LTpIA1jUOsvoV7c_51KsOj4lurjGqH_7uXo

{
  "contactNumber" : 123456788,
   "address" : "Bhupalpally abcdefghtikjjh"
}

### updating editing  password 
PATCH http://localhost:8080/api/jobprovider/editpassword
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjJkNTVjNDBkMDM3MmNjYmUxZjAiLCJpYXQiOjE1ODU3MzQ1MzQsImV4cCI6MTY0NTczNDUzNH0.34-59--3LTpIA1jUOsvoV7c_51KsOj4lurjGqH_7uXo

{
  "password":"123456"
}



###  Logging out from Provider Account
DELETE http://localhost:8080/api/jobprovider/logout/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjJkNTVjNDBkMDM3MmNjYmUxZjAiLCJpYXQiOjE1ODYwODc5MzgsImV4cCI6MTY0NjA4NzkzOH0.9-CI9amt46gntaBLQu-H1ppQUlj1L-WYKh1UJwjHylo


### forgot passsword sending system generated password
POST http://localhost:8080/api/user/forgotpassword
Content-Type: application/json

{
  "email":"harishponna55@gmail.com",
  "role":"Job-Provider",
  "aadhaarNumber":123456789123
}


#######################################  SEEKER ROUTES   ###################################3


###   Register Seeker Account
POST http://localhost:8080/api/user/register
content-type: application/json

{
  	"name": "Siddhida",
    "email":"jhasiddhida@gmail.com",
    "password":"123456",
   "aadhaarNumber" :123456789789,
  "gender":"female",
   "contactNumber" : 1234567890,
   "address" : "Ranchi abcdefghtikjjh",
   "role" : "Job-Seeker"
}

###  Account Activation
GET http://localhost:8080/api/accountactivation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MC45MjQ5NzExNjY1MjY2Njc4LCJpYXQiOjE1ODU3MzUwMjUsImV4cCI6MTY0NTczNTAyNX0.15SCcIFKUIZIcgJ64-r4YwzgVT8FmFnok5dznzCyFN8?user=Job-Seeker


###   Login into Seeker Account
POST http://localhost:8080/api/user/login
content-type: application/json

{
    "email":"jhasiddhida@gmail.com",
    "password":"123456",
    "role":"Job-Seeker"
}

### showing all jobs which are available
GET http://localhost:8080/api/jobseeker/searchjobs/allavailablejobs/1/


### filtering jobs by category of hourly, daily, weekly, monthly

GET http://localhost:8080/api/jobseeker/searchjobs/filter/1?category=hourly


### showing single job by jobId
GET http://localhost:8080/api/jobseeker/searchjobs/byjobId/1/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjU3MTEwMzQxMzJhYmM3MTkxYTUiLCJpYXQiOjE1ODU3MzUxMDAsImV4cCI6MTY0NTczNTEwMH0.YnZdcV4CmsoiEF-xpqIBf9L9k36CunmVsvdiQ5Rs42M


###   Job Accepting by Seeker
PATCH http://localhost:8080/api/jobseeker/searchjobs/byjobid/5e8463a55c40d0372ccbe1f3/isaccepted
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjU3MTEwMzQxMzJhYmM3MTkxYTUiLCJpYXQiOjE1ODU3MzUxMDAsImV4cCI6MTY0NTczNTEwMH0.YnZdcV4CmsoiEF-xpqIBf9L9k36CunmVsvdiQ5Rs42M


###  showing jobs accepted by seeker till date
GET http://localhost:8080/api/jobseeker/jobsacceptedtilldate/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjU3MTEwMzQxMzJhYmM3MTkxYTUiLCJpYXQiOjE1ODU3MzUxMDAsImV4cCI6MTY0NTczNTEwMH0.YnZdcV4CmsoiEF-xpqIBf9L9k36CunmVsvdiQ5Rs42M


###   Uploading Profile Picture
PATCH http://localhost:8080/api/jobseeker/uploadprofilepicture
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjU3MTEwMzQxMzJhYmM3MTkxYTUiLCJpYXQiOjE1ODU3MzUxMDAsImV4cCI6MTY0NTczNTEwMH0.YnZdcV4CmsoiEF-xpqIBf9L9k36CunmVsvdiQ5Rs42M

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="hari.jpeg"
Content-Type: image/jpeg

< C:\Users\Harish\Desktop\hari.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### udpating profile
PATCH http://localhost:8080/api/jobseeker/editprofile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjU3MTEwMzQxMzJhYmM3MTkxYTUiLCJpYXQiOjE1ODU3MzUxMDAsImV4cCI6MTY0NTczNTEwMH0.YnZdcV4CmsoiEF-xpqIBf9L9k36CunmVsvdiQ5Rs42M

{
  "contactNumber" : 8977777077,
   "address" : "Ranchi abcdefghtikjjh"
}


##### Edit password
PATCH http://localhost:8080/api/jobseeker/editpassword
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjU3MTEwMzQxMzJhYmM3MTkxYTUiLCJpYXQiOjE1ODU3MzUxMDAsImV4cCI6MTY0NTczNTEwMH0.YnZdcV4CmsoiEF-xpqIBf9L9k36CunmVsvdiQ5Rs42M

{
  "password":"123456"
}

###  Logging out from Seeker Account
DELETE http://localhost:8080/api/jobseeker/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTg0NjU3MTEwMzQxMzJhYmM3MTkxYTUiLCJpYXQiOjE1ODU3MzUxMDAsImV4cCI6MTY0NTczNTEwMH0.YnZdcV4CmsoiEF-xpqIBf9L9k36CunmVsvdiQ5Rs42M

### forgot passsword sending system generated password
POST http://localhost:8080/api/user/forgotpassword
Content-Type: application/json

{
  "email":"jhasiddhida@gmail.com",
  "role":"Job-Seeker",
  "aadhaarNumber":123456789789
}





######################### Admin Routes ###############################

### Loggin In

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
    "name":"admin",
    "email":"admin@gmail.com",
    "password":"admin",
    "role":"Admin"
}

### view all available(including blocked) jobs
GET http://localhost:8080/api/admin/allavailablejobs/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTgzNDNjY2ZjMTZmODFkOTg2ZmI3YTIiLCJpYXQiOjE1ODU3Mzc1MjgsImV4cCI6MTY0NTczNzUyOH0.bmcxwlr3qNLvDewPZ3NalABsjDGS-CRAU2d_S8U1nUg

### view all accepted jobs
GET http://localhost:8080/api/admin/allacceptedjobs/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTgzNDNjY2ZjMTZmODFkOTg2ZmI3YTIiLCJpYXQiOjE1ODU3Mzc1MjgsImV4cCI6MTY0NTczNzUyOH0.bmcxwlr3qNLvDewPZ3NalABsjDGS-CRAU2d_S8U1nUg

### view all Providers
GET http://localhost:8080/api/admin/allproviders/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTgzNDNjY2ZjMTZmODFkOTg2ZmI3YTIiLCJpYXQiOjE1ODU3Mzc1MjgsImV4cCI6MTY0NTczNzUyOH0.bmcxwlr3qNLvDewPZ3NalABsjDGS-CRAU2d_S8U1nUg

### view all seekers
GET http://localhost:8080/api/admin/allseekers/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTgzNDNjY2ZjMTZmODFkOTg2ZmI3YTIiLCJpYXQiOjE1ODU3Mzc1MjgsImV4cCI6MTY0NTczNzUyOH0.bmcxwlr3qNLvDewPZ3NalABsjDGS-CRAU2d_S8U1nUg

### Blocking
PATCH http://localhost:8080/api/admin/5e8465711034132abc7191a5/isblocked/?model=Job-Seeker 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTgzNDNjY2ZjMTZmODFkOTg2ZmI3YTIiLCJpYXQiOjE1ODU3Mzc1MjgsImV4cCI6MTY0NTczNzUyOH0.bmcxwlr3qNLvDewPZ3NalABsjDGS-CRAU2d_S8U1nUg

### logout
DELETE http://localhost:8080/api/admin/logout/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTgzNDNjY2ZjMTZmODFkOTg2ZmI3YTIiLCJpYXQiOjE1ODU3Mzc1MjgsImV4cCI6MTY0NTczNzUyOH0.bmcxwlr3qNLvDewPZ3NalABsjDGS-CRAU2d_S8U1nUg